# Generated by Django 3.0.5 on 2020-04-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a task name.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(help_text='Enter a text of the task', max_length=1000)),
                ('status', models.CharField(choices=[('1', 'status 1'), ('2', 'status 2'), ('3', 'status 3'), ('4', 'status 4'), ('5', 'status 5')], max_length=1)),
            ],
        ),
    ]
