# Generated by Django 3.0.5 on 2020-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200429_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(help_text='Enter a text of the task', max_length=500),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(help_text='Enter a status name', max_length=200, unique=True),
        ),
    ]
