# Generated by Django 3.0.5 on 2020-05-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200503_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(choices=[('new', 'Принят'), ('confirmed', 'Подтвержден'), ('processing', 'Обрабатывается'), ('sended', 'Отправлен'), ('canceled', 'Отменен')], default='new', help_text='Enter a status name', max_length=200, unique=True),
        ),
    ]
