# Generated by Django 3.0.5 on 2020-05-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200503_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(help_text='Enter a status name', max_length=200, unique=True),
        ),
    ]
