# Generated by Django 3.0.5 on 2020-05-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200503_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
    ]
